// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Indicator struct {
	ID            string       `json:"id"`
	Indicator     string       `json:"indicator"`
	IndicatorType string       `json:"indicator_type"`
	MetaSource    string       `json:"meta_source"`
	CreatedAt     time.Time    `json:"created_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
}

type Todo struct {
	ID        string       `json:"id"`
	Text      string       `json:"text"`
	Done      bool         `json:"done"`
	UserID    string       `json:"user_id"`
	CreatedAt time.Time    `json:"created_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type User struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt time.Time    `json:"created_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}
