// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateIndicator(ctx context.Context, arg CreateIndicatorParams) error
	CreateTodo(ctx context.Context, arg CreateTodoParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteIndicator(ctx context.Context, id string) error
	DeleteTodo(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetIndicatorByID(ctx context.Context, id string) (GetIndicatorByIDRow, error)
	GetTodoByID(ctx context.Context, id string) (GetTodoByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	ListIndicators(ctx context.Context) ([]ListIndicatorsRow, error)
	ListTodos(ctx context.Context) ([]ListTodosRow, error)
	ListTodosByUserID(ctx context.Context, userID string) ([]ListTodosByUserIDRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	RestoreUser(ctx context.Context, id string) error
	SearchIndicatorsByType(ctx context.Context, indicatorType string) ([]SearchIndicatorsByTypeRow, error)
	SoftDeleteIndicator(ctx context.Context, id string) error
	SoftDeleteTodo(ctx context.Context, id string) error
	SoftDeleteUser(ctx context.Context, id string) error
	UpdateIndicator(ctx context.Context, arg UpdateIndicatorParams) error
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
