// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: todo.sql

package db

import (
	"context"
	"time"
)

const createTodo = `-- name: CreateTodo :exec
INSERT INTO todos (id, text, done, user_id)
VALUES (?, ?, ?, ?)
`

type CreateTodoParams struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) error {
	_, err := q.db.ExecContext(ctx, createTodo,
		arg.ID,
		arg.Text,
		arg.Done,
		arg.UserID,
	)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT t.id, t.text, t.done, t.user_id, t.created_at, t.updated_at,
       u.name AS user_name, u.email AS user_email
FROM todos t
JOIN users u ON t.user_id = u.id
WHERE t.id = ? AND t.deleted_at IS NULL AND u.deleted_at IS NULL
LIMIT 1
`

type GetTodoByIDRow struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	Done      bool      `json:"done"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserName  string    `json:"user_name"`
	UserEmail string    `json:"user_email"`
}

func (q *Queries) GetTodoByID(ctx context.Context, id string) (GetTodoByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i GetTodoByIDRow
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.Done,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT t.id, t.text, t.done, t.user_id, t.created_at, t.updated_at,
       u.name AS user_name, u.email AS user_email
FROM todos t
JOIN users u ON t.user_id = u.id
WHERE t.deleted_at IS NULL AND u.deleted_at IS NULL
ORDER BY t.created_at DESC
`

type ListTodosRow struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	Done      bool      `json:"done"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserName  string    `json:"user_name"`
	UserEmail string    `json:"user_email"`
}

func (q *Queries) ListTodos(ctx context.Context) ([]ListTodosRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodosRow{}
	for rows.Next() {
		var i ListTodosRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Done,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByUserID = `-- name: ListTodosByUserID :many
SELECT t.id, t.text, t.done, t.user_id, t.created_at, t.updated_at
FROM todos t
WHERE t.user_id = ? AND t.deleted_at IS NULL
ORDER BY t.created_at DESC
`

type ListTodosByUserIDRow struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	Done      bool      `json:"done"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListTodosByUserID(ctx context.Context, userID string) ([]ListTodosByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTodosByUserIDRow{}
	for rows.Next() {
		var i ListTodosByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Text,
			&i.Done,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTodo = `-- name: SoftDeleteTodo :exec
UPDATE todos
SET deleted_at = now(), updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTodo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteTodo, id)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos
SET text = ?, done = ?, updated_at = now()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateTodoParams struct {
	Text string `json:"text"`
	Done bool   `json:"done"`
	ID   string `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo, arg.Text, arg.Done, arg.ID)
	return err
}
