// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CommentIntel interface {
	IsCommentIntel()
	GetID() string
	GetContent() string
	GetPostID() string
	GetCreatedAt() string
	GetUpdatedAt() string
}

type IndicatorIntel interface {
	IsIndicatorIntel()
	GetID() string
	GetIndicator() string
	GetIndicatorType() string
	GetMetaSource() string
}

type PostIntel interface {
	IsPostIntel()
	GetID() string
	GetTitle() string
	GetContent() string
	GetPv() int32
	GetCreatedAt() string
	GetUpdatedAt() string
}

type UserIntel interface {
	IsUserIntel()
	GetID() string
	GetName() string
	GetEmail() string
	GetPassword() string
	GetAvatar() string
	GetGender() string
	GetBio() string
	GetCreatedAt() string
	GetUpdatedAt() string
}

type Comment struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Content   string `json:"content"`
	PostID    string `json:"post_id"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	Author    *User  `json:"author"`
}

func (Comment) IsCommentIntel()           {}
func (this Comment) GetID() string        { return this.ID }
func (this Comment) GetContent() string   { return this.Content }
func (this Comment) GetPostID() string    { return this.PostID }
func (this Comment) GetCreatedAt() string { return this.CreatedAt }
func (this Comment) GetUpdatedAt() string { return this.UpdatedAt }

type CommentIDInput struct {
	ID string `json:"id"`
}

type CreateCommentInput struct {
	Content string `json:"content"`
	PostID  string `json:"post_id"`
}

type CreatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Pv      int32  `json:"pv"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Indicator struct {
	ID            string `json:"id"`
	Indicator     string `json:"indicator"`
	IndicatorType string `json:"indicatorType"`
	MetaSource    string `json:"metaSource"`
}

func (Indicator) IsIndicatorIntel()             {}
func (this Indicator) GetID() string            { return this.ID }
func (this Indicator) GetIndicator() string     { return this.Indicator }
func (this Indicator) GetIndicatorType() string { return this.IndicatorType }
func (this Indicator) GetMetaSource() string    { return this.MetaSource }

type IndicatorInput struct {
	Indicator     string `json:"indicator"`
	IndicatorType string `json:"indicatorType"`
	MetaSource    string `json:"metaSource"`
}

type Login struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Post struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Pv        int32  `json:"pv"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
	Author    *User  `json:"author"`
}

func (Post) IsPostIntel()              {}
func (this Post) GetID() string        { return this.ID }
func (this Post) GetTitle() string     { return this.Title }
func (this Post) GetContent() string   { return this.Content }
func (this Post) GetPv() int32         { return this.Pv }
func (this Post) GetCreatedAt() string { return this.CreatedAt }
func (this Post) GetUpdatedAt() string { return this.UpdatedAt }

type PostIDInput struct {
	ID string `json:"id"`
}

type PostTitleInput struct {
	Title string `json:"title"`
}

type Query struct {
}

type UpdateCommentInput struct {
	ID      string `json:"id"`
	Content string `json:"content"`
}

type UpdatePostInput struct {
	ID      string  `json:"id"`
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
	Pv      *int32  `json:"pv,omitempty"`
}

type UpdateUserInput struct {
	ID       string  `json:"id"`
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Avatar   *string `json:"avatar,omitempty"`
	Gender   *string `json:"gender,omitempty"`
	Bio      *string `json:"bio,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Avatar    string `json:"avatar"`
	Gender    string `json:"gender"`
	Bio       string `json:"bio"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (User) IsUserIntel()              {}
func (this User) GetID() string        { return this.ID }
func (this User) GetName() string      { return this.Name }
func (this User) GetEmail() string     { return this.Email }
func (this User) GetPassword() string  { return this.Password }
func (this User) GetAvatar() string    { return this.Avatar }
func (this User) GetGender() string    { return this.Gender }
func (this User) GetBio() string       { return this.Bio }
func (this User) GetCreatedAt() string { return this.CreatedAt }
func (this User) GetUpdatedAt() string { return this.UpdatedAt }

type UserEmailInput struct {
	Email string `json:"email"`
}

type UserIDInput struct {
	ID string `json:"id"`
}

type UserNameInput struct {
	Name string `json:"name"`
}
