// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: comment.sql

package db

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (id, user_id, content, post_id)
VALUES (?, ?, ?, ?)
`

type CreateCommentParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Content string `json:"content"`
	PostID  string `json:"post_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.PostID,
	)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.user_id, c.content, c.post_id, c.created_at, c.updated_at,
       u.name AS user_name, u.email AS user_email, u.avatar AS user_avatar, 
       u.gender AS user_gender, u.bio AS user_bio
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.id = ? AND c.deleted_at IS NULL AND u.deleted_at IS NULL
LIMIT 1
`

type GetCommentByIDRow struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	Content    string         `json:"content"`
	PostID     string         `json:"post_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	UserName   string         `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserAvatar string         `json:"user_avatar"`
	UserGender sql.NullString `json:"user_gender"`
	UserBio    string         `json:"user_bio"`
}

func (q *Queries) GetCommentByID(ctx context.Context, id string) (GetCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.PostID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatar,
		&i.UserGender,
		&i.UserBio,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.user_id, c.content, c.post_id, c.created_at, c.updated_at,
       u.name AS user_name, u.email AS user_email, u.avatar AS user_avatar, 
       u.gender AS user_gender, u.bio AS user_bio
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.deleted_at IS NULL AND u.deleted_at IS NULL
ORDER BY c.created_at DESC
`

type ListCommentsRow struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	Content    string         `json:"content"`
	PostID     string         `json:"post_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	UserName   string         `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserAvatar string         `json:"user_avatar"`
	UserGender sql.NullString `json:"user_gender"`
	UserBio    string         `json:"user_bio"`
}

func (q *Queries) ListComments(ctx context.Context) ([]ListCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.PostID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
			&i.UserGender,
			&i.UserBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByContent = `-- name: ListCommentsByContent :many
SELECT c.id, c.user_id, c.content, c.post_id, c.created_at, c.updated_at,
       u.name AS user_name, u.email AS user_email, u.avatar AS user_avatar, 
       u.gender AS user_gender, u.bio AS user_bio
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE INSTR(c.content, ?) > 0 AND c.deleted_at IS NULL AND u.deleted_at IS NULL
ORDER BY c.created_at DESC
`

type ListCommentsByContentRow struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	Content    string         `json:"content"`
	PostID     string         `json:"post_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	UserName   string         `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserAvatar string         `json:"user_avatar"`
	UserGender sql.NullString `json:"user_gender"`
	UserBio    string         `json:"user_bio"`
}

func (q *Queries) ListCommentsByContent(ctx context.Context, instr string) ([]ListCommentsByContentRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByContent, instr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByContentRow{}
	for rows.Next() {
		var i ListCommentsByContentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.PostID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
			&i.UserGender,
			&i.UserBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByPostID = `-- name: ListCommentsByPostID :many
SELECT c.id, c.user_id, c.content, c.post_id, c.created_at, c.updated_at,
       u.name AS user_name, u.email AS user_email, u.avatar AS user_avatar, 
       u.gender AS user_gender, u.bio AS user_bio
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.post_id = ? AND c.deleted_at IS NULL AND u.deleted_at IS NULL
ORDER BY c.created_at DESC
`

type ListCommentsByPostIDRow struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	Content    string         `json:"content"`
	PostID     string         `json:"post_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	UserName   string         `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserAvatar string         `json:"user_avatar"`
	UserGender sql.NullString `json:"user_gender"`
	UserBio    string         `json:"user_bio"`
}

func (q *Queries) ListCommentsByPostID(ctx context.Context, postID string) ([]ListCommentsByPostIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByPostIDRow{}
	for rows.Next() {
		var i ListCommentsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.PostID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
			&i.UserGender,
			&i.UserBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByUserID = `-- name: ListCommentsByUserID :many
SELECT c.id, c.user_id, c.content, c.post_id, c.created_at, c.updated_at,
       u.name AS user_name, u.email AS user_email, u.avatar AS user_avatar, 
       u.gender AS user_gender, u.bio AS user_bio
FROM comments c
JOIN users u ON c.user_id = u.id
WHERE c.user_id = ? AND c.deleted_at IS NULL AND u.deleted_at IS NULL
ORDER BY c.created_at DESC
`

type ListCommentsByUserIDRow struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	Content    string         `json:"content"`
	PostID     string         `json:"post_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	UserName   string         `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserAvatar string         `json:"user_avatar"`
	UserGender sql.NullString `json:"user_gender"`
	UserBio    string         `json:"user_bio"`
}

func (q *Queries) ListCommentsByUserID(ctx context.Context, userID string) ([]ListCommentsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByUserIDRow{}
	for rows.Next() {
		var i ListCommentsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.PostID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
			&i.UserGender,
			&i.UserBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreComment = `-- name: RestoreComment :exec
UPDATE comments
SET deleted_at = NULL, updated_at = datetime('now', 'localtime')
WHERE id = ?
`

func (q *Queries) RestoreComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, restoreComment, id)
	return err
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments
SET deleted_at = datetime('now', 'localtime'), updated_at = datetime('now', 'localtime')
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteComment, id)
	return err
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments
SET user_id = ?, content = ?, post_id = ?, updated_at = datetime('now', 'localtime')
WHERE id = ? AND deleted_at IS NULL
`

type UpdateCommentParams struct {
	UserID  string `json:"user_id"`
	Content string `json:"content"`
	PostID  string `json:"post_id"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment,
		arg.UserID,
		arg.Content,
		arg.PostID,
		arg.ID,
	)
	return err
}
