// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: indicator.sql

package db

import (
	"context"
)

const createIndicator = `-- name: CreateIndicator :exec
INSERT INTO indicators (id, indicator, indicator_type, meta_source)
VALUES (?, ?, ?, ?)
`

type CreateIndicatorParams struct {
	ID            string `json:"id"`
	Indicator     string `json:"indicator"`
	IndicatorType string `json:"indicator_type"`
	MetaSource    string `json:"meta_source"`
}

func (q *Queries) CreateIndicator(ctx context.Context, arg CreateIndicatorParams) error {
	_, err := q.db.ExecContext(ctx, createIndicator,
		arg.ID,
		arg.Indicator,
		arg.IndicatorType,
		arg.MetaSource,
	)
	return err
}

const deleteIndicator = `-- name: DeleteIndicator :exec
DELETE FROM indicators WHERE id = ?
`

func (q *Queries) DeleteIndicator(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIndicator, id)
	return err
}

const getIndicatorByID = `-- name: GetIndicatorByID :one
SELECT id, indicator, indicator_type, meta_source, created_at, updated_at
FROM indicators
WHERE id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetIndicatorByIDRow struct {
	ID            string `json:"id"`
	Indicator     string `json:"indicator"`
	IndicatorType string `json:"indicator_type"`
	MetaSource    string `json:"meta_source"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) GetIndicatorByID(ctx context.Context, id string) (GetIndicatorByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getIndicatorByID, id)
	var i GetIndicatorByIDRow
	err := row.Scan(
		&i.ID,
		&i.Indicator,
		&i.IndicatorType,
		&i.MetaSource,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIndicators = `-- name: ListIndicators :many
SELECT id, indicator, indicator_type, meta_source, created_at, updated_at
FROM indicators
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

type ListIndicatorsRow struct {
	ID            string `json:"id"`
	Indicator     string `json:"indicator"`
	IndicatorType string `json:"indicator_type"`
	MetaSource    string `json:"meta_source"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) ListIndicators(ctx context.Context) ([]ListIndicatorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIndicators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIndicatorsRow{}
	for rows.Next() {
		var i ListIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Indicator,
			&i.IndicatorType,
			&i.MetaSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchIndicatorsByType = `-- name: SearchIndicatorsByType :many
SELECT id, indicator, indicator_type, meta_source, created_at, updated_at
FROM indicators
WHERE indicator_type = ? AND deleted_at IS NULL
ORDER BY created_at DESC
`

type SearchIndicatorsByTypeRow struct {
	ID            string `json:"id"`
	Indicator     string `json:"indicator"`
	IndicatorType string `json:"indicator_type"`
	MetaSource    string `json:"meta_source"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

func (q *Queries) SearchIndicatorsByType(ctx context.Context, indicatorType string) ([]SearchIndicatorsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, searchIndicatorsByType, indicatorType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchIndicatorsByTypeRow{}
	for rows.Next() {
		var i SearchIndicatorsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Indicator,
			&i.IndicatorType,
			&i.MetaSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteIndicator = `-- name: SoftDeleteIndicator :exec
UPDATE indicators
SET deleted_at = datetime('now', 'localtime'), updated_at = datetime('now', 'localtime')
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteIndicator(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteIndicator, id)
	return err
}

const updateIndicator = `-- name: UpdateIndicator :exec
UPDATE indicators
SET indicator = ?, indicator_type = ?, meta_source = ?, updated_at = datetime('now', 'localtime')
WHERE id = ? AND deleted_at IS NULL
`

type UpdateIndicatorParams struct {
	Indicator     string `json:"indicator"`
	IndicatorType string `json:"indicator_type"`
	MetaSource    string `json:"meta_source"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateIndicator(ctx context.Context, arg UpdateIndicatorParams) error {
	_, err := q.db.ExecContext(ctx, updateIndicator,
		arg.Indicator,
		arg.IndicatorType,
		arg.MetaSource,
		arg.ID,
	)
	return err
}
