// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Comment struct {
	ID        string      `json:"id"`
	UserID    string      `json:"user_id"`
	Content   string      `json:"content"`
	PostID    string      `json:"post_id"`
	CreatedAt string      `json:"created_at"`
	UpdatedAt string      `json:"updated_at"`
	DeletedAt interface{} `json:"deleted_at"`
}

type Indicator struct {
	ID            string      `json:"id"`
	Indicator     string      `json:"indicator"`
	IndicatorType string      `json:"indicator_type"`
	MetaSource    string      `json:"meta_source"`
	CreatedAt     string      `json:"created_at"`
	UpdatedAt     string      `json:"updated_at"`
	DeletedAt     interface{} `json:"deleted_at"`
}

type Post struct {
	ID        string        `json:"id"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	Pv        sql.NullInt64 `json:"pv"`
	UserID    string        `json:"user_id"`
	CreatedAt string        `json:"created_at"`
	UpdatedAt string        `json:"updated_at"`
	DeletedAt interface{}   `json:"deleted_at"`
}

type User struct {
	ID        string         `json:"id"`
	Email     string         `json:"email"`
	Name      string         `json:"name"`
	Password  string         `json:"password"`
	Avatar    string         `json:"avatar"`
	Gender    sql.NullString `json:"gender"`
	Bio       string         `json:"bio"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
	DeletedAt interface{}    `json:"deleted_at"`
}
