// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post.sql

package db

import (
	"context"
	"database/sql"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (id, title, content, pv, user_id)
VALUES (?, ?, ?, ?, ?)
`

type CreatePostParams struct {
	ID      string        `json:"id"`
	Title   string        `json:"title"`
	Content string        `json:"content"`
	Pv      sql.NullInt64 `json:"pv"`
	UserID  string        `json:"user_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Pv,
		arg.UserID,
	)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = ?
`

func (q *Queries) DeletePost(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT p.id, p.title, p.content, p.pv, p.user_id, p.created_at, p.updated_at,
       u.name AS user_name, u.email AS user_email, u.avatar AS user_avatar, 
       u.gender AS user_gender, u.bio AS user_bio
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.id = ? AND p.deleted_at IS NULL AND u.deleted_at IS NULL
LIMIT 1
`

type GetPostByIDRow struct {
	ID         string         `json:"id"`
	Title      string         `json:"title"`
	Content    string         `json:"content"`
	Pv         sql.NullInt64  `json:"pv"`
	UserID     string         `json:"user_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	UserName   string         `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserAvatar string         `json:"user_avatar"`
	UserGender sql.NullString `json:"user_gender"`
	UserBio    string         `json:"user_bio"`
}

func (q *Queries) GetPostByID(ctx context.Context, id string) (GetPostByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Pv,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.UserAvatar,
		&i.UserGender,
		&i.UserBio,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT p.id, p.title, p.content, p.pv, p.user_id, p.created_at, p.updated_at,
       u.name AS user_name, u.email AS user_email, u.avatar AS user_avatar, 
       u.gender AS user_gender, u.bio AS user_bio
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.deleted_at IS NULL AND u.deleted_at IS NULL
ORDER BY p.created_at DESC
`

type ListPostsRow struct {
	ID         string         `json:"id"`
	Title      string         `json:"title"`
	Content    string         `json:"content"`
	Pv         sql.NullInt64  `json:"pv"`
	UserID     string         `json:"user_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	UserName   string         `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserAvatar string         `json:"user_avatar"`
	UserGender sql.NullString `json:"user_gender"`
	UserBio    string         `json:"user_bio"`
}

func (q *Queries) ListPosts(ctx context.Context) ([]ListPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRow{}
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Pv,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
			&i.UserGender,
			&i.UserBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTitle = `-- name: ListPostsByTitle :many
SELECT p.id, p.title, p.content, p.pv, p.user_id, p.created_at, p.updated_at,
       u.name AS user_name, u.email AS user_email, u.avatar AS user_avatar, 
       u.gender AS user_gender, u.bio AS user_bio
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE INSTR(p.title, ?) > 0 AND p.deleted_at IS NULL AND u.deleted_at IS NULL
ORDER BY p.created_at DESC
`

type ListPostsByTitleRow struct {
	ID         string         `json:"id"`
	Title      string         `json:"title"`
	Content    string         `json:"content"`
	Pv         sql.NullInt64  `json:"pv"`
	UserID     string         `json:"user_id"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	UserName   string         `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserAvatar string         `json:"user_avatar"`
	UserGender sql.NullString `json:"user_gender"`
	UserBio    string         `json:"user_bio"`
}

func (q *Queries) ListPostsByTitle(ctx context.Context, instr string) ([]ListPostsByTitleRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByTitle, instr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByTitleRow{}
	for rows.Next() {
		var i ListPostsByTitleRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Pv,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
			&i.UserGender,
			&i.UserBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePost = `-- name: RestorePost :exec
UPDATE posts
SET deleted_at = NULL, updated_at = datetime('now', 'localtime')
WHERE id = ?
`

func (q *Queries) RestorePost(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, restorePost, id)
	return err
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts
SET deleted_at = datetime('now', 'localtime'), updated_at = datetime('now', 'localtime')
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePost(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeletePost, id)
	return err
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET title = ?, content = ?, pv = ?, user_id = ?, updated_at = datetime('now', 'localtime')
WHERE id = ? AND deleted_at IS NULL
`

type UpdatePostParams struct {
	Title   string        `json:"title"`
	Content string        `json:"content"`
	Pv      sql.NullInt64 `json:"pv"`
	UserID  string        `json:"user_id"`
	ID      string        `json:"id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Title,
		arg.Content,
		arg.Pv,
		arg.UserID,
		arg.ID,
	)
	return err
}
