// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) error
	CreateIndicator(ctx context.Context, arg CreateIndicatorParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteComment(ctx context.Context, id string) error
	DeleteIndicator(ctx context.Context, id string) error
	DeletePost(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	GetCommentByID(ctx context.Context, id string) (GetCommentByIDRow, error)
	GetIndicatorByID(ctx context.Context, id string) (GetIndicatorByIDRow, error)
	GetPostByID(ctx context.Context, id string) (GetPostByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByName(ctx context.Context, name string) (GetUserByNameRow, error)
	ListComments(ctx context.Context) ([]ListCommentsRow, error)
	ListCommentsByContent(ctx context.Context, instr string) ([]ListCommentsByContentRow, error)
	ListCommentsByPostID(ctx context.Context, postID string) ([]ListCommentsByPostIDRow, error)
	ListCommentsByUserID(ctx context.Context, userID string) ([]ListCommentsByUserIDRow, error)
	ListIndicators(ctx context.Context) ([]ListIndicatorsRow, error)
	ListPosts(ctx context.Context) ([]ListPostsRow, error)
	ListPostsByTitle(ctx context.Context, instr string) ([]ListPostsByTitleRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	RestoreComment(ctx context.Context, id string) error
	RestorePost(ctx context.Context, id string) error
	RestoreUser(ctx context.Context, id string) error
	SearchIndicatorsByType(ctx context.Context, indicatorType string) ([]SearchIndicatorsByTypeRow, error)
	SoftDeleteComment(ctx context.Context, id string) error
	SoftDeleteIndicator(ctx context.Context, id string) error
	SoftDeletePost(ctx context.Context, id string) error
	SoftDeleteUser(ctx context.Context, id string) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) error
	UpdateIndicator(ctx context.Context, arg UpdateIndicatorParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
