// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: comment.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (id, content, author, post_id, deleted_type, deleted_at)
VALUES ($1, $2, $3, $4, 0, NULL)
`

type CreateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
	Author  uuid.UUID `json:"author"`
	PostID  uuid.UUID `json:"post_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.ID,
		arg.Content,
		arg.Author,
		arg.PostID,
	)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const listComments = `-- name: ListComments :many
SELECT
  c.id,
  c.content,
  c.post_id,
  c.created_at,
  c.updated_at,
  u.id AS user_id,
  u.name AS user_name,
  u.email AS user_email,
  u.avatar AS user_avatar,
  u.gender AS user_gender,
  u.bio AS user_bio
FROM comments c
JOIN users u ON c.author = u.id
WHERE ($1::text IS NULL OR c.content ILIKE '%' || $1 || '%')  -- content参数有值则匹配
  AND ($2::text IS NULL OR c.author = $2)  -- author参数有值则匹配
	AND ($3::text IS NULL OR c.post_id = $3)  -- post_id参数有值则匹配
  AND ($4::text IS NULL OR c.id = $4)  -- id参数有值则匹配
  AND c.deleted_at IS NULL
  AND u.deleted_at IS NULL
ORDER BY c.created_at DESC
`

type ListCommentsParams struct {
	Content string `json:"content"`
	Author  string `json:"author"`
	PostID  string `json:"post_id"`
	ID      string `json:"id"`
}

type ListCommentsRow struct {
	ID         uuid.UUID      `json:"id"`
	Content    string         `json:"content"`
	PostID     uuid.UUID      `json:"post_id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	UserID     uuid.UUID      `json:"user_id"`
	UserName   string         `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserAvatar string         `json:"user_avatar"`
	UserGender sql.NullString `json:"user_gender"`
	UserBio    string         `json:"user_bio"`
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComments,
		arg.Content,
		arg.Author,
		arg.PostID,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsRow{}
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.PostID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
			&i.UserGender,
			&i.UserBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreComment = `-- name: RestoreComment :exec
UPDATE comments
SET
  deleted_type = 0,
  deleted_at = NULL,
  updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, restoreComment, id)
	return err
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments
SET
  deleted_at = now(),
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteComment, id)
	return err
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments
SET
  content = coalesce($2, content),
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, content, updated_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID      `json:"id"`
	Content sql.NullString `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.ID, arg.Content)
	return err
}
