// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: indicator.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createIndicator = `-- name: CreateIndicator :exec
INSERT INTO indicators (id, indicator, indicator_type, meta_source)
VALUES ($1, $2, $3, $4)
`

type CreateIndicatorParams struct {
	ID            uuid.UUID `json:"id"`
	Indicator     string    `json:"indicator"`
	IndicatorType string    `json:"indicator_type"`
	MetaSource    string    `json:"meta_source"`
}

func (q *Queries) CreateIndicator(ctx context.Context, arg CreateIndicatorParams) error {
	_, err := q.db.ExecContext(ctx, createIndicator,
		arg.ID,
		arg.Indicator,
		arg.IndicatorType,
		arg.MetaSource,
	)
	return err
}

const deleteIndicator = `-- name: DeleteIndicator :exec
DELETE FROM indicators
WHERE id = $1
`

func (q *Queries) DeleteIndicator(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteIndicator, id)
	return err
}

const listIndicators = `-- name: ListIndicators :many
SELECT id, indicator, indicator_type, meta_source, created_at, updated_at
FROM indicators
WHERE ($3::text IS NULL OR indicator ILIKE '%' || $3 || '%')  -- indicator参数有值则匹配
  AND ($4::text IS NULL OR indicator_type ILIKE '%' || $4 || '%')  -- indicator_type参数有值则匹配
  AND ($5::text IS NULL OR meta_source ILIKE '%' || $5 || '%')  -- meta_source参数有值则匹配
  AND ($6::text IS NULL OR id = $6)  -- id参数有值则匹配
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListIndicatorsParams struct {
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
	Indicator     string `json:"indicator"`
	IndicatorType string `json:"indicator_type"`
	MetaSource    string `json:"meta_source"`
	ID            string `json:"id"`
}

type ListIndicatorsRow struct {
	ID            uuid.UUID `json:"id"`
	Indicator     string    `json:"indicator"`
	IndicatorType string    `json:"indicator_type"`
	MetaSource    string    `json:"meta_source"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

func (q *Queries) ListIndicators(ctx context.Context, arg ListIndicatorsParams) ([]ListIndicatorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIndicators,
		arg.Limit,
		arg.Offset,
		arg.Indicator,
		arg.IndicatorType,
		arg.MetaSource,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIndicatorsRow{}
	for rows.Next() {
		var i ListIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Indicator,
			&i.IndicatorType,
			&i.MetaSource,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteIndicator = `-- name: SoftDeleteIndicator :exec
UPDATE indicators
SET
    deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteIndicator(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteIndicator, id)
	return err
}

const updateIndicator = `-- name: UpdateIndicator :exec
UPDATE indicators
SET
    indicator = coalesce($2, indicator),
    indicator_type = coalesce($3, indicator_type),
    meta_source = coalesce($4, meta_source),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, indicator, indicator_type, meta_source, updated_at
`

type UpdateIndicatorParams struct {
	ID            uuid.UUID      `json:"id"`
	Indicator     sql.NullString `json:"indicator"`
	IndicatorType sql.NullString `json:"indicator_type"`
	MetaSource    sql.NullString `json:"meta_source"`
}

func (q *Queries) UpdateIndicator(ctx context.Context, arg UpdateIndicatorParams) error {
	_, err := q.db.ExecContext(ctx, updateIndicator,
		arg.ID,
		arg.Indicator,
		arg.IndicatorType,
		arg.MetaSource,
	)
	return err
}
