// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID          uuid.UUID     `json:"id"`
	Author      uuid.UUID     `json:"author"`
	Content     string        `json:"content"`
	PostID      uuid.UUID     `json:"post_id"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	DeletedType sql.NullInt16 `json:"deleted_type"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
}

type Indicator struct {
	ID            uuid.UUID    `json:"id"`
	Indicator     string       `json:"indicator"`
	IndicatorType string       `json:"indicator_type"`
	MetaSource    string       `json:"meta_source"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

type Post struct {
	ID          uuid.UUID     `json:"id"`
	Author      uuid.UUID     `json:"author"`
	Title       string        `json:"title"`
	Content     string        `json:"content"`
	Pv          int32         `json:"pv"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
	DeletedType sql.NullInt16 `json:"deleted_type"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	Email       string         `json:"email"`
	Name        string         `json:"name"`
	Password    string         `json:"password"`
	Avatar      string         `json:"avatar"`
	Gender      sql.NullString `json:"gender"`
	Bio         string         `json:"bio"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedType sql.NullInt16  `json:"deleted_type"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}
