// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: post.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO
    posts (
        id,
        title,
        content,
        pv,
        author,
        deleted_type,
        deleted_at
    )
VALUES ($1, $2, $3, $4, $5, 0, NULL)
`

type CreatePostParams struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
	Pv      int32     `json:"pv"`
	Author  uuid.UUID `json:"author"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Pv,
		arg.Author,
	)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const listPosts = `-- name: ListPosts :many
SELECT 
  p.id,
  p.title,
  p.content,
  p.pv,
  p.created_at,
  p.updated_at,
  u.id AS user_id,
  u.name AS user_name,
  u.email AS user_email,
  u.avatar AS user_avatar,
  u.gender AS user_gender,
  u.bio AS user_bio
FROM posts p
JOIN users u ON p.author = u.id
WHERE 
  ($3::text IS NULL OR p.title ILIKE '%' || $3 || '%')  -- title有值则匹配标题
  AND ($4::text IS NULL OR p.content ILIKE '%' || $4 || '%')  -- content有值则匹配内容
  AND ($5::integer IS NULL OR p.pv = $5)  -- pv有值则匹配浏览量
  AND ($6::text IS NULL OR p.author = $6)  -- author有值则匹配用户
  AND ($7::text IS NULL OR p.id = $7)  -- id参数有值则匹配
  AND p.deleted_at IS NULL
  AND p.deleted_type = 0
  AND u.deleted_at IS NULL
  AND u.deleted_type = 0
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Pv      int32  `json:"pv"`
	Author  string `json:"author"`
	ID      string `json:"id"`
}

type ListPostsRow struct {
	ID         uuid.UUID      `json:"id"`
	Title      string         `json:"title"`
	Content    string         `json:"content"`
	Pv         int32          `json:"pv"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	UserID     uuid.UUID      `json:"user_id"`
	UserName   string         `json:"user_name"`
	UserEmail  string         `json:"user_email"`
	UserAvatar string         `json:"user_avatar"`
	UserGender sql.NullString `json:"user_gender"`
	UserBio    string         `json:"user_bio"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPosts,
		arg.Limit,
		arg.Offset,
		arg.Title,
		arg.Content,
		arg.Pv,
		arg.Author,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsRow{}
	for rows.Next() {
		var i ListPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Pv,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
			&i.UserGender,
			&i.UserBio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsForAdmin = `-- name: ListPostsForAdmin :many
SELECT
	p.id,
  p.title,
  p.content,
  p.pv,
  p.created_at,
  p.updated_at,
  p.deleted_type,
  p.deleted_at,
  u.id AS user_id,
  u.name AS user_name,
  u.email AS user_email,
  u.avatar AS user_avatar,
  u.gender AS user_gender,
  u.bio AS user_bio,
  u.deleted_type AS user_deleted_type,
  u.deleted_at AS user_deleted_at
FROM posts p
JOIN users u ON p.author = u.id
WHERE ($3::text IS NULL OR p.title ILIKE '%' || $3 || '%')  -- title有值则按title筛选
  AND ($4::text IS NULL OR p.content ILIKE '%' || $4 || '%')  -- content有值则按content筛选
  AND ($5::integer IS NULL OR p.pv = $5)  -- pv有值则按pv筛选
  AND ($6::text IS NULL OR p.author = $6)  -- author有值则匹配用户
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsForAdminParams struct {
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Pv      int32  `json:"pv"`
	Author  string `json:"author"`
}

type ListPostsForAdminRow struct {
	ID              uuid.UUID      `json:"id"`
	Title           string         `json:"title"`
	Content         string         `json:"content"`
	Pv              int32          `json:"pv"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedType     sql.NullInt16  `json:"deleted_type"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	UserID          uuid.UUID      `json:"user_id"`
	UserName        string         `json:"user_name"`
	UserEmail       string         `json:"user_email"`
	UserAvatar      string         `json:"user_avatar"`
	UserGender      sql.NullString `json:"user_gender"`
	UserBio         string         `json:"user_bio"`
	UserDeletedType sql.NullInt16  `json:"user_deleted_type"`
	UserDeletedAt   sql.NullTime   `json:"user_deleted_at"`
}

func (q *Queries) ListPostsForAdmin(ctx context.Context, arg ListPostsForAdminParams) ([]ListPostsForAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsForAdmin,
		arg.Limit,
		arg.Offset,
		arg.Title,
		arg.Content,
		arg.Pv,
		arg.Author,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsForAdminRow{}
	for rows.Next() {
		var i ListPostsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Pv,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedType,
			&i.DeletedAt,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatar,
			&i.UserGender,
			&i.UserBio,
			&i.UserDeletedType,
			&i.UserDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePost = `-- name: RestorePost :exec
UPDATE posts
SET
    deleted_type = 0,
    deleted_at = NULL,
    updated_at = now()
WHERE
    id = $1
`

func (q *Queries) RestorePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, restorePost, id)
	return err
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts
SET
    deleted_type = 1,
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND deleted_at IS NULL
    AND deleted_type = 0
`

func (q *Queries) SoftDeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeletePost, id)
	return err
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET
    title = coalesce($2, title),
    content = coalesce($3, content),
    author = coalesce($4, author),
    updated_at = now()
WHERE
    id = $1
    AND deleted_at IS NULL
    AND deleted_type = 0 RETURNING id,
    title,
    content,
    author,
    updated_at
`

type UpdatePostParams struct {
	ID      uuid.UUID      `json:"id"`
	Title   sql.NullString `json:"title"`
	Content sql.NullString `json:"content"`
	Author  uuid.NullUUID  `json:"author"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Author,
	)
	return err
}
