// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) error
	CreateIndicator(ctx context.Context, arg CreateIndicatorParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteComment(ctx context.Context, id uuid.UUID) error
	DeleteIndicator(ctx context.Context, id uuid.UUID) error
	DeletePost(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error)
	ListIndicators(ctx context.Context, arg ListIndicatorsParams) ([]ListIndicatorsRow, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error)
	ListPostsForAdmin(ctx context.Context, arg ListPostsForAdminParams) ([]ListPostsForAdminRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error)
	RestoreComment(ctx context.Context, id uuid.UUID) error
	RestorePost(ctx context.Context, id uuid.UUID) error
	RestoreUser(ctx context.Context, id uuid.UUID) error
	SoftDeleteComment(ctx context.Context, id uuid.UUID) error
	SoftDeleteIndicator(ctx context.Context, id uuid.UUID) error
	SoftDeletePost(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) error
	UpdateIndicator(ctx context.Context, arg UpdateIndicatorParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
