// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO
    users (
        id,
        name,
        email,
        password,
        avatar,
        gender,
        bio,
        deleted_type,
        deleted_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        0,
        NULL
    )
`

type CreateUserParams struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Avatar   string         `json:"avatar"`
	Gender   sql.NullString `json:"gender"`
	Bio      string         `json:"bio"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Avatar,
		arg.Gender,
		arg.Bio,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password, avatar, gender, bio, created_at, updated_at
FROM users
WHERE ($3::text IS NULL OR name ILIKE '%' || $3 || '%')  -- name参数有值则匹配
  AND ($4::text IS NULL OR email ILIKE '%' || $4 || '%')  -- email参数有值则匹配
  AND ($5::text IS NULL OR id = $5)  -- id参数有值则匹配
  AND deleted_at IS NULL AND deleted_type = 0
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	ID     string `json:"id"`
}

type ListUsersRow struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	Avatar    string         `json:"avatar"`
	Gender    sql.NullString `json:"gender"`
	Bio       string         `json:"bio"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers,
		arg.Limit,
		arg.Offset,
		arg.Name,
		arg.Email,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Avatar,
			&i.Gender,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many
SELECT id, name, email, password, avatar, gender, bio, created_at, updated_at, deleted_type, deleted_at
FROM users
WHERE ($3::text IS NULL OR name ILIKE '%' || $3 || '%')  -- name参数有值则匹配
  AND ($4::text IS NULL OR email ILIKE '%' || $4 || '%')  -- email参数有值则匹配
  AND ($5::text IS NULL OR TRIM(gender) = $5)  -- gender参数有值则匹配
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersForAdminParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Name   string `json:"name"`
	Email  string `json:"email"`
	Gender string `json:"gender"`
}

type ListUsersForAdminRow struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Email       string         `json:"email"`
	Password    string         `json:"password"`
	Avatar      string         `json:"avatar"`
	Gender      sql.NullString `json:"gender"`
	Bio         string         `json:"bio"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	DeletedType sql.NullInt16  `json:"deleted_type"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsersForAdmin,
		arg.Limit,
		arg.Offset,
		arg.Name,
		arg.Email,
		arg.Gender,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersForAdminRow{}
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Avatar,
			&i.Gender,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedType,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users
SET
    deleted_type = 0,
    deleted_at = NULL,
    updated_at = now()
WHERE
    id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, restoreUser, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET
    deleted_type = 1,
    deleted_at = now(),
    updated_at = now()
WHERE
    id = $1
    AND deleted_at IS NULL
    AND deleted_type = 0
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    name = coalesce($3, name),
    email = coalesce($4, email),
    password = coalesce($5, password),
    avatar = coalesce($6, avatar),
    gender = coalesce($7, gender),
    bio = COALESCE($1, bio),
    updated_at = now()
WHERE
    id = $2
    AND deleted_at IS NULL
    AND deleted_type = 0 RETURNING id,
    name,
    email,
    password,
    avatar,
    gender,
    bio,
    updated_at
`

type UpdateUserParams struct {
	Bio      string         `json:"bio"`
	ID       uuid.UUID      `json:"id"`
	Name     sql.NullString `json:"name"`
	Email    sql.NullString `json:"email"`
	Password sql.NullString `json:"password"`
	Avatar   sql.NullString `json:"avatar"`
	Gender   sql.NullString `json:"gender"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Bio,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Avatar,
		arg.Gender,
	)
	return err
}
