package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/thkx/graphql-sqlc-go-dome/internal/graph/model"
)

// CreateIndicator is the resolver for the createIndicator field.
func (r *mutationResolver) CreateIndicator(ctx context.Context, input model.IndicatorInput) (*model.Indicator, error) {
	panic(fmt.Errorf("not implemented: CreateIndicator - createIndicator"))
}

// Indicators is the resolver for the indicators field.
func (r *queryResolver) Indicators(ctx context.Context) ([]*model.Indicator, error) {
	panic(fmt.Errorf("not implemented: Indicators - indicators"))
}
