package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/thkx/graphql-sqlc-go-dome/internal/graph/model"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	panic(fmt.Errorf("not implemented: CreatePost - createPost"))
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input model.UpdatePostInput) (*model.Post, error) {
	panic(fmt.Errorf("not implemented: UpdatePost - updatePost"))
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, input model.PostIDInput) (string, error) {
	panic(fmt.Errorf("not implemented: DeletePost - deletePost"))
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: Posts - posts"))
}

// GetPostByID is the resolver for the getPostById field.
func (r *queryResolver) GetPostByID(ctx context.Context, input model.PostIDInput) (*model.Post, error) {
	panic(fmt.Errorf("not implemented: GetPostByID - getPostById"))
}

// GetPostByUserID is the resolver for the getPostByUserID field.
func (r *queryResolver) GetPostByUserID(ctx context.Context, input model.UserIDInput) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: GetPostByUserID - getPostByUserID"))
}

// GetPostByTitle is the resolver for the getPostByTitle field.
func (r *queryResolver) GetPostByTitle(ctx context.Context, input model.PostTitleInput) ([]*model.Post, error) {
	panic(fmt.Errorf("not implemented: GetPostByTitle - getPostByTitle"))
}
