package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"github.com/thkx/graphql-sqlc-go-dome/internal/auth"
	"github.com/thkx/graphql-sqlc-go-dome/internal/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	// panic(fmt.Errorf("not implemented: CreateUser - createUser"))
	log.Println("graph.CreateUser()")
	err := r.Resolver.u.CreateUser(ctx, input)
	return &model.User{}, err
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, input model.UserIDInput) (string, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input *model.LoginInput) (*model.Login, error) {
	// panic(fmt.Errorf("not implemented: Login - login"))
	log.Println("graph.Login()")
	w, _ := ctx.Value(auth.RespWriter).(http.ResponseWriter)
	return r.Resolver.u.Login(ctx, *input, w)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	// panic(fmt.Errorf("not implemented: Users - users"))
	log.Println("graph.Users()")
	return r.Resolver.u.ListUsers(ctx)
}

// GetUserByID is the resolver for the getUserById field.
func (r *queryResolver) GetUserByID(ctx context.Context, input *model.UserIDInput) (*model.User, error) {
	// panic(fmt.Errorf("not implemented: GetUserByID - getUserById"))
	log.Println("graph.GetUserByID()")
	return r.Resolver.u.GetUserByID(ctx, input.ID)
}
